### ISSUE TITLE
check_diaganol

### ISSUE THREAD

**Issue by vlastikczech** [firehose-fire/chess#53]
```
  def check_diaganol(x_target, y_target)
    x = coordinate_x
    y = coordinate_y

    #top to bottom and left to right
    while x < x_target do 
      x = x + 1 
      y = y -1
      return true if is_occupied?(x, y)
    end

    #top to bottom and right to left
    while x > x_target do 
      x = x - 1 
      y = y - 1
      return true if is_occupied?(x, y)
    end

    #bottom to top and right to left
    while x > x_target do 
      x = x - 1 
      y = y + 1
      return true if is_occupied?(x, y)
    end

    #bottom to top and left to right
    while y < y_target do 
      x = x + 1 
      y = y + 1
      return true if is_occupied?(x, y)
    end

    return false
  end
```

method  to be worked on. Doesn't even hit the conditions and just returns false

**Comment by corymichaelhack** [comment]
The only part of that method that is not functioning properly should be the  
#bottom to top and left to right
    while y < y_target do 
      x = x + 1 
      y = y + 1
      return true if is_occupied?(x, y)
    end

I made a note about that in the spec testing and the pull request. 

You should be able to go any other diagonal direction just fine and return the correct coordinates. Let me know if that is incorrect.
